[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
lto = true

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.126"

[build-dependencies]
bindgen = "0.60.1"
