[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[profile.release]
# strip = true
lto = true
codegen-units = 1
opt-level = "z"

[lib]
crate-type = ["staticlib"]

[build-dependencies]
bindgen = "0.60.1"
