[package]
name = "rust"
version = "0.8.0"
edition = "2021"

[profile.release]
strip = "debuginfo"
panic = "abort"
lto = true
codegen-units = 1

[lib]
crate-type = ["staticlib"]

[build-dependencies]
bindgen = "0.60.1"
