#ifndef _RUST_H_
#define _RUST_H_

/* Generated with cbindgen:0.24.3 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include "intermediate.h"


void make_output(Quad quad);

#endif /* _RUST_H_ */
